WEB_153502_FEDORINCHIK/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WEB_153502_FEDORINCHIK.Domain.Models;
using WEB_153502_FEDORINCHIK.Extensions;
using WEB_153502_FEDORINCHIK.Services.GameService;

namespace WEB_153502_FEDORINCHIK.Controllers
{
    public class CartController : Controller
    {
        private readonly IGameService _gameService;
        private readonly Cart _cart;
        public CartController(IGameService gameService, Cart cart)
        {
            _gameService = gameService;
            _cart = cart;
        }


        [Authorize]
        [Route("[controller]")]
        public IActionResult Index()
        {
            return View(_cart.CartItems);
        }


        [Authorize]
        [Route("[controller]/add/{id:int}")]
        public async Task<IActionResult> Add(int id, string returnUrl)
        {
            var response = await _gameService.GetGameByIdAsync(id);
            if (response.Success)
            {
                _cart.AddToCart(response.Data!);
            }

            return Redirect(returnUrl);
        }


        [Authorize]
        [Route("[controller]/remove/{id:int}")]
        public async Task<ActionResult> Remove(int id, string returnUrl)
        {
            await Task.Run(() => _cart.RemoveItems(id));
            return Redirect(returnUrl);
        }
    }
}

WEB_153502_FEDORINCHIK/Controllers/IdentityController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Security.Policy;

namespace WEB_153502_FEDORINCHIK.Controllers
{
    public class IdentityController : Controller
    {
        public async Task Login()
        {
            await HttpContext.ChallengeAsync(
                "oidc",
                new AuthenticationProperties
                {
                    RedirectUri = Url.Action("Index", "Home")
                }
            );
        }

        [HttpPost]
        public async Task Logout()
        {
            await HttpContext.SignOutAsync("cookie");
            await HttpContext.SignOutAsync("oidc",
                new AuthenticationProperties
                {
                    RedirectUri = Url.Action("Index", "Home")
                });
        }
    }
}

WEB_153502_FEDORINCHIK/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WEB_153502_FEDORINCHIK.Domain.Entities;
using WEB_153502_FEDORINCHIK.Domain.Models;
using WEB_153502_FEDORINCHIK.Extensions;
using WEB_153502_FEDORINCHIK.Services.GameGenreService;
using WEB_153502_FEDORINCHIK.Services.GameService;

namespace WEB_153502_FEDORINCHIK.Controllers
{

    public class ProductController : Controller
    {
        private IGameGenreService _gameGenreService;
        private IGameService _gameService;

        public ProductController(IGameService gameService, IGameGenreService gameGenreService)
        {
            _gameGenreService = gameGenreService;
            _gameService = gameService;
        }

        [Route("Catalog")]
        [Route("Catalog/{gameGenreNormalized?}")]
        public async Task<IActionResult> Index(string? gameGenreNormalized, int pageNo = 1)
        {
            var genresResponse = await _gameGenreService.GetGameGenreListAsync();
            if (!genresResponse.Success)
                return NotFound(genresResponse.ErrorMessage);

            var genres = genresResponse.Data;

            ViewData["genres"] = genres;
            ViewData["currentGenre"] =
                gameGenreNormalized == null ?
                new GameGenre { Name = "Все", NormalizedName = null } :
                genres?.SingleOrDefault(g=> g.NormalizedName == gameGenreNormalized);


            if (gameGenreNormalized == "Все")
                gameGenreNormalized = null;

            var gameResponse = await _gameService.GetGameListAsync(gameGenreNormalized, pageNo);
            if (!gameResponse.Success)
                return NotFound(gameResponse.ErrorMessage);

            if (Request.IsAjaxRequest())
            {
                ListModel<Game> data = gameResponse.Data!;
                return PartialView("_ProductIndexPartial", new
                {
                    Items = data.Items,
                    CurrentPage = pageNo,
                    TotalPages =  data.TotalPages,
                    GameGenreNormalized = gameGenreNormalized
                });
            }
            else
            {
                //return View(new ListModel<Game>
                //{
                //    Items = gameResponse.Data.Items,
                //    CurrentPage = pageNo,
                //    TotalPages = gameResponse.Data.TotalPages,
                //});
                return View(gameResponse.Data);
            }
            
        }
    }
}

WEB_153502_FEDORINCHIK/Views/Shared/DEL_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WEB_153502_FEDORINCHIK</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WEB_153502_FEDORINCHIK.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WEB_153502_FEDORINCHIK</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WEB_153502_FEDORINCHIK - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WEB_153502_FEDORINCHIK/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
    <link rel="stylesheet" href="~/WEB_153502_FEDORINCHIK.styles.css" asp-append-version="true" />
</head>


<body>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>



    <header>
        <div class="container">
            <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            
                <partial name="_MenuPartial" />              

                <partial name="_UserInfoPartial" />
         
            </nav> 
        </div>  
    </header>


    <main class="container">
        @RenderBody()
    </main>


    <footer>
        <div class="container">
            <div class="navbar navbar-dark navbar-expand-md bg-dark">
                <div class="navbar-nav ms-auto">
                    <a class="nav-item nav-link" href="http://www.facebook.com">
                        <i class="fa-brands fa-facebook-f fa-2x"></i>
                    </a>
                    <a class="nav-item nav-link" href="http://www.vk.com">
                        <i class="fa-brands fa-vk fa-2x"></i>
                    </a>
                    <a class="nav-item nav-link" href="http://www.twitter.com">
                        <i class="fa-brands fa-twitter fa-2x"></i>
                    </a>
                </div>
            </div>
        </div>
    </footer>


    @await RenderSectionAsync("Scripts", false)
</body>

</html>

WEB_153502_FEDORINCHIK/Views/Shared/_MenuPartial.cshtml
@{
    var controller = ViewContext.RouteData.Values["controller"]?.ToString()?.ToLower() ?? String.Empty;
    var area = ViewContext.RouteData.Values["area"]?.ToString()?.ToLower() ?? String.Empty;
}

<a class="navbar-brand" asp-controller="Home" asp-action="Index">WebLabs</a>
<div class="navbar-nav">
    <a class="nav-item nav-link @(controller == "home" ? "active" : "")" asp-controller="Home" asp-action="Index">Лб 1</a>
    <a class="nav-item nav-link @(controller == "product" ? "active" : "")" asp-controller="Product" asp-action="Index">Каталог</a>
    <a class="nav-item nav-link @(area == "admin" ? "active" : "")" asp-area="Admin" asp-page="/Index">Администрирование</a>
</div>

WEB_153502_FEDORINCHIK/Views/Shared/_ProductIndexPartial.cshtml
@{
    var request = ViewContext.HttpContext.Request;
    var returnUrl = request.Path + request.QueryString.ToUriComponent();
}

@foreach (var item in Model.Items)
{
    <div class="col-md-4">
        <div class="card" style="width: 20rem;">
            <img src="@item.Path" class="card-img-top" alt="Game Image">
            <div class="card-body">
                <h5 class="card-title">@item.Name</h5>
                <p class="card-text">@item.Description</p>
                <p class="card-text">@item.Price USD</p>
                <a asp-controller="Cart" asp-action="Add" asp-route-id="@item.Id" asp-route-returnurl="@returnUrl" class="btn btn-primary">Add to cart</a>
            </div>
        </div>
    </div>
}

<br>
<br>

<Pager current-page="@Model.CurrentPage"
       total-pages="@Model.TotalPages"
       category="@(Model.GameGenreNormalized)">
   </Pager>

WEB_153502_FEDORINCHIK/Views/Shared/_UserInfoPartial.cshtml
@{
    var userName = User.Claims.FirstOrDefault(c =>
        c.Type.Equals("Name", StringComparison.OrdinalIgnoreCase))?.Value;
}

@if (User.Identity!.IsAuthenticated)
{
    @await Component.InvokeAsync("Cart")

    <div class="dropdown ms-4 nav-color">
        <button class="btn btn-secondary dropdown-toggle"
                type="button" id="dropdownMenuButton"
                data-bs-toggle="dropdown"
                aria-expanded="false">
            @userName
            <img src="https://localhost:7003/avatar" width="30"
                 alt="@userName" class="rounded nav-color" />
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <li>
                <span class="dropdown-item-text">
                    <img src="https://localhost:7003/avatar"
                         width="50" alt="Avatar" class="rounded" />
                    @userName
                </span>
            </li>

            <li><hr class="dropdown-divider" /></li>

            <li>
                <form id="logoutForm" class="form-inline" asp-controller="Identity" asp-action="Logout">
                    <button id="logout" type="submit" class="nav-link btn btn-link text-dark ms-2">
                        Logout
                    </button>
                </form>
            </li>
        </ul>
    </div>

}
else
{
    <div class="ms-auto">
        <form id="loginForm" class="form-inline" asp-controller="Identity" asp-action="Login">
            <button id="login" type="submit" class="nav-link btn btn-link text-white">
                Login
            </button>
        </form>
    </div>

}